//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeLanguage
    {
        public short AttributeID { get; set; }
        public string LanguageCode { get; set; }
        public string AttributeName { get; set; }
    
        public virtual Attribute Attribute { get; set; }
    }
}
