//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryAttribute
    {
        public int CategoryAttributeID { get; set; }
        public short CategoryID { get; set; }
        public short AttributeID { get; set; }
        public short AttributeSequence { get; set; }
        public bool IsMandatory { get; set; }
        public Nullable<double> MinFloatValue { get; set; }
        public Nullable<double> MaxFloatValue { get; set; }
        public Nullable<short> UOMID { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual Category Category { get; set; }
        public virtual UOM UOM { get; set; }
    }
}
