//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckListTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CheckListTask()
        {
            this.CheckListTaskDeviationTypes = new HashSet<CheckListTaskDeviationType>();
            this.CheckListTaskLanguages = new HashSet<CheckListTaskLanguage>();
            this.Deviations = new HashSet<Deviation>();
            this.ObjectInstanceTasks = new HashSet<ObjectInstanceTask>();
        }
    
        public int CheckListTaskID { get; set; }
        public Nullable<short> ChecklistTaskGroupID { get; set; }
        public short CheckListID { get; set; }
        public string CheckListTaskCode { get; set; }
        public short TaskSequence { get; set; }
        public bool IsMandatory { get; set; }
        public string AttributeType { get; set; }
        public Nullable<short> TextLength { get; set; }
        public Nullable<byte> FloatPrecision { get; set; }
        public Nullable<byte> FloatScale { get; set; }
        public Nullable<short> UOMID { get; set; }
        public Nullable<bool> DeviationIfFalse { get; set; }
        public Nullable<short> BoolDeviationTypeID { get; set; }
        public Nullable<double> DeviationIfLessValue { get; set; }
        public Nullable<short> LessValueDeviationTypeID { get; set; }
        public Nullable<double> DeviationIfMoreValue { get; set; }
        public Nullable<short> MoreValueDeviationTypeID { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTill { get; set; }
    
        public virtual CheckList CheckList { get; set; }
        public virtual DeviationType DeviationType { get; set; }
        public virtual ChecklistTaskGroup ChecklistTaskGroup { get; set; }
        public virtual DeviationType DeviationType1 { get; set; }
        public virtual DeviationType DeviationType2 { get; set; }
        public virtual UOM UOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckListTaskDeviationType> CheckListTaskDeviationTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckListTaskLanguage> CheckListTaskLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deviation> Deviations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectInstanceTask> ObjectInstanceTasks { get; set; }
    }
}
