//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CheckList()
        {
            this.AdditionalFrequencyCheckLists = new HashSet<AdditionalFrequencyCheckList>();
            this.AdditionalFrequencyCheckLists1 = new HashSet<AdditionalFrequencyCheckList>();
            this.CheckListTasks = new HashSet<CheckListTask>();
            this.Inspections = new HashSet<Inspection>();
            this.InspectionCheckLists = new HashSet<InspectionCheckList>();
        }
    
        public short CheckListID { get; set; }
        public short CategoryID { get; set; }
        public string InspectionType { get; set; }
        public string Frequency { get; set; }
        public Nullable<byte> ServiceLevelID { get; set; }
        public Nullable<byte> ExecutionDuration { get; set; }
        public string ExecutionUnit { get; set; }
        public Nullable<short> CustomerID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionalFrequencyCheckList> AdditionalFrequencyCheckLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionalFrequencyCheckList> AdditionalFrequencyCheckLists1 { get; set; }
        public virtual Category Category { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckListTask> CheckListTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspection> Inspections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionCheckList> InspectionCheckLists { get; set; }
    }
}
