//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChecklistTaskGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChecklistTaskGroup()
        {
            this.CheckListTasks = new HashSet<CheckListTask>();
            this.DeviationTypes = new HashSet<DeviationType>();
            this.ChecklistTaskGroupLanguages = new HashSet<ChecklistTaskGroupLanguage>();
            this.DrillCheckListTasks = new HashSet<DrillCheckListTask>();
            this.FRASCheckListTasks = new HashSet<FRASCheckListTask>();
            this.IncidentCheckListTasks = new HashSet<IncidentCheckListTask>();
            this.WorkCheckListTasks = new HashSet<WorkCheckListTask>();
        }
    
        public short ChecklistTaskGroupID { get; set; }
        public string ModuleCode { get; set; }
        public short GroupSequence { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckListTask> CheckListTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviationType> DeviationTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChecklistTaskGroupLanguage> ChecklistTaskGroupLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrillCheckListTask> DrillCheckListTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FRASCheckListTask> FRASCheckListTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentCheckListTask> IncidentCheckListTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkCheckListTask> WorkCheckListTasks { get; set; }
    }
}
