//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.ContractCategories = new HashSet<ContractCategory>();
            this.ContractLocations = new HashSet<ContractLocation>();
            this.Inspections = new HashSet<Inspection>();
        }
    
        public int ContractID { get; set; }
        public short CustomerID { get; set; }
        public System.DateTime ContractDate { get; set; }
        public System.DateTime ContractStartDate { get; set; }
        public string InspectionType { get; set; }
        public byte ContractDuration { get; set; }
        public string SourceRefID { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> SalesPersonID { get; set; }
        public Nullable<int> ResponsiblePersonID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual EndUser EndUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractCategory> ContractCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractLocation> ContractLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspection> Inspections { get; set; }
        public virtual EndUser EndUser1 { get; set; }
    }
}
