//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControllerSpecialization
    {
        public int ControllerID { get; set; }
        public string ServiceLineCode { get; set; }
        public Nullable<short> CategoryID { get; set; }
        public string InspectionType { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual EndUser EndUser { get; set; }
    }
}
