//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractCategory
    {
        public int ContractID { get; set; }
        public short CategoryID { get; set; }
        public Nullable<byte> ServiceLevelID { get; set; }
        public string Frequency { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Contract Contract { get; set; }
    }
}
