//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseDocument
    {
        public int CourseDocumentID { get; set; }
        public short CourseID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public string CourseLink { get; set; }
        public string Title { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
