//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLocationHoliday
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerLocationHoliday()
        {
            this.CustomerLocationHolidayNames = new HashSet<CustomerLocationHolidayName>();
        }
    
        public int CustomerLocationID { get; set; }
        public System.DateTime HolidayDate { get; set; }
    
        public virtual CustomerLocation CustomerLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerLocationHolidayName> CustomerLocationHolidayNames { get; set; }
    }
}
