//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerIRemark
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerIRemark()
        {
            this.Inspections = new HashSet<Inspection>();
        }
    
        public int CustomerIRemarksID { get; set; }
        public short CustomerID { get; set; }
        public string CustomerConfirmationPerson { get; set; }
        public Nullable<long> CustomerSignatureImage { get; set; }
        public System.DateTime CustomerSignatureDateTime { get; set; }
        public string CustomerRemarks { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual FolderFile FolderFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspection> Inspections { get; set; }
    }
}
