//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesignationCourse
    {
        public short DesignationID { get; set; }
        public short CourseID { get; set; }
        public string Remarks { get; set; }
        public System.DateTime EffectiveFromDateTime { get; set; }
        public Nullable<System.DateTime> EffectiveTillDateTime { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Designation Designation { get; set; }
    }
}
