//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviationTypeResolutionRepairComponent
    {
        public int DeviationTypeResolutionID { get; set; }
        public Nullable<short> ObjectID { get; set; }
        public short RepairComponentID { get; set; }
        public Nullable<double> MaxUseQuantity { get; set; }
        public Nullable<double> DefaultQuantity { get; set; }
    
        public virtual DeviationTypeResolution DeviationTypeResolution { get; set; }
        public virtual Object Object { get; set; }
        public virtual RepairComponent RepairComponent { get; set; }
    }
}
