//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviationTypeDepartment
    {
        public short DeviationTypeID { get; set; }
        public short DepartmentID { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual DeviationType DeviationType { get; set; }
    }
}
