//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviationResolutionRemarksPhoto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeviationResolutionRemarksPhoto()
        {
            this.DeviationResolutionRemarksPhotoElements = new HashSet<DeviationResolutionRemarksPhotoElement>();
        }
    
        public long DeviationID { get; set; }
        public System.DateTime PhotoDateTime { get; set; }
        public string Remarks { get; set; }
    
        public virtual Deviation Deviation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviationResolutionRemarksPhotoElement> DeviationResolutionRemarksPhotoElements { get; set; }
    }
}
