//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviationRepairComponent
    {
        public long DeviationID { get; set; }
        public short RepairComponentID { get; set; }
        public Nullable<double> UsedQuantity { get; set; }
        public Nullable<double> RequiredQuantity { get; set; }
    
        public virtual Deviation Deviation { get; set; }
        public virtual RepairComponent RepairComponent { get; set; }
    }
}
