//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviationTypeResolution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeviationTypeResolution()
        {
            this.DeviationTypeResolutionLanguages = new HashSet<DeviationTypeResolutionLanguage>();
            this.DeviationTypeResolutionRepairComponents = new HashSet<DeviationTypeResolutionRepairComponent>();
            this.Deviations = new HashSet<Deviation>();
        }
    
        public int DeviationTypeResolutionID { get; set; }
        public short DeviationTypeID { get; set; }
        public short ResolutionSequence { get; set; }
        public Nullable<byte> ResolutionDuration { get; set; }
        public string ResolutionUnit { get; set; }
        public bool CanAddRepairComponent { get; set; }
        public Nullable<bool> UseRepairComponents { get; set; }
    
        public virtual DeviationType DeviationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviationTypeResolutionLanguage> DeviationTypeResolutionLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviationTypeResolutionRepairComponent> DeviationTypeResolutionRepairComponents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deviation> Deviations { get; set; }
    }
}
