//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviationType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeviationType()
        {
            this.CheckListTasks = new HashSet<CheckListTask>();
            this.CheckListTasks1 = new HashSet<CheckListTask>();
            this.CheckListTasks2 = new HashSet<CheckListTask>();
            this.CheckListTaskDeviationTypes = new HashSet<CheckListTaskDeviationType>();
            this.Deviations = new HashSet<Deviation>();
            this.DeviationTypeDepartments = new HashSet<DeviationTypeDepartment>();
            this.DeviationTypeLanguages = new HashSet<DeviationTypeLanguage>();
            this.DeviationTypeResolutions = new HashSet<DeviationTypeResolution>();
        }
    
        public short DeviationTypeID { get; set; }
        public string ServiceLineCode { get; set; }
        public Nullable<short> CategoryID { get; set; }
        public byte RiskLevelID { get; set; }
        public string DeviationTypeCode { get; set; }
        public short DeviationTypeSequence { get; set; }
        public Nullable<byte> ResolutionDuration { get; set; }
        public string ResolutionUnit { get; set; }
        public Nullable<short> DeviationGroupID { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckListTask> CheckListTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckListTask> CheckListTasks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckListTask> CheckListTasks2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckListTaskDeviationType> CheckListTaskDeviationTypes { get; set; }
        public virtual ChecklistTaskGroup ChecklistTaskGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deviation> Deviations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviationTypeDepartment> DeviationTypeDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviationTypeLanguage> DeviationTypeLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviationTypeResolution> DeviationTypeResolutions { get; set; }
    }
}
