//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deviation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deviation()
        {
            this.DeviationLocationPhotoes = new HashSet<DeviationLocationPhoto>();
            this.DeviationRepairComponents = new HashSet<DeviationRepairComponent>();
            this.DeviationResolutionRemarksPhotoes = new HashSet<DeviationResolutionRemarksPhoto>();
            this.DeviationResolutionRemarksPhotoElements = new HashSet<DeviationResolutionRemarksPhotoElement>();
            this.ObjectDeviationPhotoes = new HashSet<ObjectDeviationPhoto>();
            this.ResolutionInspectionDeviations = new HashSet<ResolutionInspectionDeviation>();
            this.DeviationTypeResolutions = new HashSet<DeviationTypeResolution>();
        }
    
        public long DeviationID { get; set; }
        public int InspectionID { get; set; }
        public int LocationID { get; set; }
        public Nullable<int> ObjectInstanceID { get; set; }
        public Nullable<int> CheckListTaskID { get; set; }
        public Nullable<short> DeviationTypeID { get; set; }
        public string DeviationDescription { get; set; }
        public System.DateTime DeviationDateTime { get; set; }
        public string DeviationRemarks { get; set; }
        public int ControllerID { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<System.DateTime> ProposedResolutionDateTime { get; set; }
        public Nullable<System.DateTime> ResolutionDateTime { get; set; }
        public Nullable<System.DateTime> ClosureDateTime { get; set; }
        public Nullable<int> ResolutionControllerID { get; set; }
        public string ResolutionRemarks { get; set; }
    
        public virtual CheckListTask CheckListTask { get; set; }
        public virtual EndUser EndUser { get; set; }
        public virtual DeviationType DeviationType { get; set; }
        public virtual Inspection Inspection { get; set; }
        public virtual Location Location { get; set; }
        public virtual ObjectInstance ObjectInstance { get; set; }
        public virtual EndUser EndUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviationLocationPhoto> DeviationLocationPhotoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviationRepairComponent> DeviationRepairComponents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviationResolutionRemarksPhoto> DeviationResolutionRemarksPhotoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviationResolutionRemarksPhotoElement> DeviationResolutionRemarksPhotoElements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectDeviationPhoto> ObjectDeviationPhotoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResolutionInspectionDeviation> ResolutionInspectionDeviations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviationTypeResolution> DeviationTypeResolutions { get; set; }
    }
}
