//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.DocumentMappings = new HashSet<DocumentMapping>();
        }
    
        public int DocumentID { get; set; }
        public short DocumentCategoryID { get; set; }
        public string DocumentNumber { get; set; }
        public string DocumentName { get; set; }
        public byte DocumentTypeID { get; set; }
        public Nullable<long> FileID { get; set; }
    
        public virtual DocumentCategory DocumentCategory { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual FolderFile FolderFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentMapping> DocumentMappings { get; set; }
    }
}
