//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrillCheckList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DrillCheckList()
        {
            this.DrillCheckListTasks = new HashSet<DrillCheckListTask>();
        }
    
        public short DrillCheckListID { get; set; }
        public byte DrillTypeID { get; set; }
        public Nullable<short> DrillStakeHolderID { get; set; }
        public string Remarks { get; set; }
    
        public virtual DrillType DrillType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrillCheckListTask> DrillCheckListTasks { get; set; }
    }
}
