//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrillCheckListTaskView
    {
        public int DrillCheckListTaskID { get; set; }
        public short DrillCheckListID { get; set; }
        public Nullable<short> ChecklistTaskGroupID { get; set; }
        public short TaskSequence { get; set; }
        public bool IsMandatory { get; set; }
        public string AttributeType { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTill { get; set; }
        public string LanguageCode { get; set; }
        public string DrillCheckListTaskName { get; set; }
    }
}
