//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrillDataPhoto
    {
        public int DrillDataID { get; set; }
        public long Photo { get; set; }
        public long SmallPhoto { get; set; }
        public byte PhotoSequence { get; set; }
        public bool ActionPhoto { get; set; }
        public bool ResolutionPhoto { get; set; }
        public bool ClosurePhoto { get; set; }
    
        public virtual DrillData DrillData { get; set; }
        public virtual FolderFile FolderFile { get; set; }
        public virtual FolderFile FolderFile1 { get; set; }
    }
}
