//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrillData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DrillData()
        {
            this.DrillDataPhotoes = new HashSet<DrillDataPhoto>();
        }
    
        public int DrillDataID { get; set; }
        public int DrillSetupID { get; set; }
        public int DrillCheckListTaskID { get; set; }
        public string AttributeType { get; set; }
        public Nullable<byte> FloatPrecision { get; set; }
        public Nullable<byte> FloatScale { get; set; }
        public Nullable<short> UOMID { get; set; }
        public Nullable<double> ExpectedMinValue { get; set; }
        public Nullable<double> ExpectedMaxValue { get; set; }
        public Nullable<bool> ExpectedBit { get; set; }
        public Nullable<System.TimeSpan> ExpectedTime { get; set; }
        public Nullable<double> ActualValue { get; set; }
        public Nullable<bool> ActualBit { get; set; }
        public Nullable<System.TimeSpan> ActualTime { get; set; }
        public string ActualText { get; set; }
        public Nullable<long> ActualPhoto { get; set; }
        public Nullable<long> ActualSmallPhoto { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsDeviation { get; set; }
        public Nullable<byte> DrillActionTypeID { get; set; }
        public Nullable<int> ActionBy { get; set; }
        public Nullable<System.DateTime> ActionDateTime { get; set; }
        public string ActionRemarks { get; set; }
        public Nullable<int> ResolvedBy { get; set; }
        public Nullable<System.DateTime> ResolutionDateTime { get; set; }
        public string ResolutionRemarks { get; set; }
        public Nullable<int> ClosedBy { get; set; }
        public Nullable<System.DateTime> ClosedDateTime { get; set; }
        public string ClosureRemarks { get; set; }
    
        public virtual DrillActionType DrillActionType { get; set; }
        public virtual DrillCheckListTask DrillCheckListTask { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual FolderFile FolderFile { get; set; }
        public virtual FolderFile FolderFile1 { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual DrillSetup DrillSetup { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual UOM UOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrillDataPhoto> DrillDataPhotoes { get; set; }
    }
}
