//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrillSetup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DrillSetup()
        {
            this.DrillDatas = new HashSet<DrillData>();
            this.DrillProposals = new HashSet<DrillProposal>();
            this.DrillProposalStatus = new HashSet<DrillProposalStatu>();
        }
    
        public int DrillSetupID { get; set; }
        public int DrillID { get; set; }
        public short DrillStakeholderID { get; set; }
        public bool IsParticipant { get; set; }
        public bool IsObserver { get; set; }
        public bool ToReport { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string Remarks { get; set; }
    
        public virtual Drill Drill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrillData> DrillDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrillProposal> DrillProposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrillProposalStatu> DrillProposalStatus { get; set; }
        public virtual DrillStakeholder DrillStakeholder { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
