//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrillProposalStatu
    {
        public int DrillProposalID { get; set; }
        public int DrillSetupID { get; set; }
        public bool IsApproved { get; set; }
        public System.DateTime ActionDatetime { get; set; }
        public string Remarks { get; set; }
    
        public virtual DrillProposal DrillProposal { get; set; }
        public virtual DrillSetup DrillSetup { get; set; }
    }
}
