//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrillCheckListTaskLanguage
    {
        public int DrillCheckListTaskID { get; set; }
        public string LanguageCode { get; set; }
        public string DrillCheckListTaskName { get; set; }
    
        public virtual DrillCheckListTask DrillCheckListTask { get; set; }
    }
}
