//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrillCheckListTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DrillCheckListTask()
        {
            this.DrillCheckListTaskLanguages = new HashSet<DrillCheckListTaskLanguage>();
            this.DrillDatas = new HashSet<DrillData>();
        }
    
        public int DrillCheckListTaskID { get; set; }
        public short DrillCheckListID { get; set; }
        public short TaskSequence { get; set; }
        public bool IsMandatory { get; set; }
        public Nullable<short> CheckListTaskGroupID { get; set; }
        public string AttributeType { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTill { get; set; }
    
        public virtual ChecklistTaskGroup ChecklistTaskGroup { get; set; }
        public virtual DrillCheckList DrillCheckList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrillCheckListTaskLanguage> DrillCheckListTaskLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrillData> DrillDatas { get; set; }
    }
}
