//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Drill()
        {
            this.DrillProposals = new HashSet<DrillProposal>();
            this.DrillSetups = new HashSet<DrillSetup>();
        }
    
        public int DrillID { get; set; }
        public byte DrillTypeID { get; set; }
        public System.DateTime DrillDatetime { get; set; }
        public int LocationID { get; set; }
        public string DrillTitle { get; set; }
        public string Remarks { get; set; }
        public System.DateTime InitiationDateTime { get; set; }
        public System.DateTime ConclusionDateTime { get; set; }
        public int OwnerID { get; set; }
        public Nullable<int> ResolutionBy { get; set; }
        public Nullable<System.DateTime> ResolutionDateTime { get; set; }
        public string ResolutionRemarks { get; set; }
        public Nullable<int> ClosedBy { get; set; }
        public Nullable<System.DateTime> ClosureDateTime { get; set; }
        public string ClosureRemarks { get; set; }
        public byte[] DrillIdentity { get; set; }
        public Nullable<bool> IsDrillDateFinalized { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual DrillType DrillType { get; set; }
        public virtual Location Location { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrillProposal> DrillProposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrillSetup> DrillSetups { get; set; }
    }
}
