//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrillProposal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DrillProposal()
        {
            this.DrillProposalStatus = new HashSet<DrillProposalStatu>();
            this.DrillProposal1 = new HashSet<DrillProposal>();
        }
    
        public int DrillProposalID { get; set; }
        public int DrillID { get; set; }
        public Nullable<int> DrillSetupID { get; set; }
        public System.DateTime ProposedDrillDatetime { get; set; }
        public string ProposalRemarks { get; set; }
        public Nullable<int> ParentDrillProposalID { get; set; }
    
        public virtual Drill Drill { get; set; }
        public virtual DrillSetup DrillSetup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrillProposalStatu> DrillProposalStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrillProposal> DrillProposal1 { get; set; }
        public virtual DrillProposal DrillProposal2 { get; set; }
    }
}
