//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeView
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string HRMSEmployeeID { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string ShortCode { get; set; }
        public string FullEmployeeAddress { get; set; }
        public string TelephoneNo { get; set; }
        public string CellNo { get; set; }
        public string ExtensionNo { get; set; }
        public string Email { get; set; }
        public string EmergencyContact1 { get; set; }
        public string EmergencyContact2 { get; set; }
        public Nullable<int> ReportingEmployeeID { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public short DesignationID { get; set; }
        public short DepartmentID { get; set; }
        public Nullable<int> EndUserID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string ReportingEmployeeName { get; set; }
        public string CustomerName { get; set; }
        public Nullable<short> CustomerID { get; set; }
    }
}
