//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EndUser()
        {
            this.Contracts = new HashSet<Contract>();
            this.ContractScheduledLocations = new HashSet<ContractScheduledLocation>();
            this.ControllerTaggings = new HashSet<ControllerTagging>();
            this.Customers = new HashSet<Customer>();
            this.CustomerContacts = new HashSet<CustomerContact>();
            this.Deviations = new HashSet<Deviation>();
            this.Deviations1 = new HashSet<Deviation>();
            this.Employees = new HashSet<Employee>();
            this.ControllerSpecializations = new HashSet<ControllerSpecialization>();
            this.EndUserModules = new HashSet<EndUserModule>();
            this.FRASInspections = new HashSet<FRASInspection>();
            this.IncidentInspections = new HashSet<IncidentInspection>();
            this.Inspections = new HashSet<Inspection>();
            this.ObjectInstanceInspections = new HashSet<ObjectInstanceInspection>();
            this.Trainings = new HashSet<Training>();
            this.UserLocations = new HashSet<UserLocation>();
            this.WorkInspections = new HashSet<WorkInspection>();
            this.WorkPermits = new HashSet<WorkPermit>();
            this.UserRoles = new HashSet<UserRole>();
            this.Locations = new HashSet<Location>();
            this.Contracts1 = new HashSet<Contract>();
        }
    
        public int EndUserID { get; set; }
        public string LoginID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string LanguageCode { get; set; }
        public decimal UTCOffset { get; set; }
        public string DefaultModuleCode { get; set; }
        public string Gender { get; set; }
        public string EmailID { get; set; }
        public byte[] UserIdentity { get; set; }
        public Nullable<System.DateTime> ActivatedDTM { get; set; }
        public string LastAccessPoint { get; set; }
        public Nullable<System.DateTime> LastLoginDTM { get; set; }
        public string SecretQuestion { get; set; }
        public string SecretAnswer { get; set; }
        public Nullable<int> ActivationURLID { get; set; }
        public Nullable<int> ResetPasswordURLID { get; set; }
        public string DeviceID { get; set; }
        public Nullable<short> DesignationID { get; set; }
        public Nullable<short> DepartmentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractScheduledLocation> ContractScheduledLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControllerTagging> ControllerTaggings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerContact> CustomerContacts { get; set; }
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deviation> Deviations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deviation> Deviations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControllerSpecialization> ControllerSpecializations { get; set; }
        public virtual PublishedURL PublishedURL { get; set; }
        public virtual PublishedURL PublishedURL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EndUserModule> EndUserModules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FRASInspection> FRASInspections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentInspection> IncidentInspections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspection> Inspections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectInstanceInspection> ObjectInstanceInspections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Training> Trainings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLocation> UserLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkInspection> WorkInspections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkPermit> WorkPermits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRole> UserRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Location> Locations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts1 { get; set; }
    }
}
