//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FolderFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FolderFile()
        {
            this.Customers = new HashSet<Customer>();
            this.CustomerIRemarks = new HashSet<CustomerIRemark>();
            this.DeviationLocationPhotoElements = new HashSet<DeviationLocationPhotoElement>();
            this.DeviationLocationPhotoElements1 = new HashSet<DeviationLocationPhotoElement>();
            this.Documents = new HashSet<Document>();
            this.DrillDatas = new HashSet<DrillData>();
            this.DrillDatas1 = new HashSet<DrillData>();
            this.DeviationResolutionRemarksPhotoElements = new HashSet<DeviationResolutionRemarksPhotoElement>();
            this.DeviationResolutionRemarksPhotoElements1 = new HashSet<DeviationResolutionRemarksPhotoElement>();
            this.DrillDataPhotoes = new HashSet<DrillDataPhoto>();
            this.DrillDataPhotoes1 = new HashSet<DrillDataPhoto>();
            this.FRASInspectionPhotoes = new HashSet<FRASInspectionPhoto>();
            this.FRASInspectionPhotoes1 = new HashSet<FRASInspectionPhoto>();
            this.IncidentAttachments = new HashSet<IncidentAttachment>();
            this.IncidentInspectionPhotoes = new HashSet<IncidentInspectionPhoto>();
            this.IncidentInspectionPhotoes1 = new HashSet<IncidentInspectionPhoto>();
            this.IncidentInspectionTasks = new HashSet<IncidentInspectionTask>();
            this.IncidentInspectionTasks1 = new HashSet<IncidentInspectionTask>();
            this.ObjectDeviationPhotoElements = new HashSet<ObjectDeviationPhotoElement>();
            this.ObjectDeviationPhotoElements1 = new HashSet<ObjectDeviationPhotoElement>();
            this.ObjectInstancePhotoElements = new HashSet<ObjectInstancePhotoElement>();
            this.ObjectInstancePhotoElements1 = new HashSet<ObjectInstancePhotoElement>();
            this.ObjectInstanceTasks = new HashSet<ObjectInstanceTask>();
            this.ObjectInstanceTasks1 = new HashSet<ObjectInstanceTask>();
            this.WorkInspectionTasks = new HashSet<WorkInspectionTask>();
            this.WorkInspectionTasks1 = new HashSet<WorkInspectionTask>();
        }
    
        public long FileID { get; set; }
        public Nullable<int> FolderID { get; set; }
        public string ObjectType { get; set; }
        public int ObjectInstanceID { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public long FileSize { get; set; }
        public string FileRemarks { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<System.DateTime> LastAccessDateTime { get; set; }
        public Nullable<System.DateTime> DeletedDateTime { get; set; }
        public int AccessCount { get; set; }
        public byte[] TxnTimestamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerIRemark> CustomerIRemarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviationLocationPhotoElement> DeviationLocationPhotoElements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviationLocationPhotoElement> DeviationLocationPhotoElements1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrillData> DrillDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrillData> DrillDatas1 { get; set; }
        public virtual Folder Folder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviationResolutionRemarksPhotoElement> DeviationResolutionRemarksPhotoElements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviationResolutionRemarksPhotoElement> DeviationResolutionRemarksPhotoElements1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrillDataPhoto> DrillDataPhotoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrillDataPhoto> DrillDataPhotoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FRASInspectionPhoto> FRASInspectionPhotoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FRASInspectionPhoto> FRASInspectionPhotoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentAttachment> IncidentAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentInspectionPhoto> IncidentInspectionPhotoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentInspectionPhoto> IncidentInspectionPhotoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentInspectionTask> IncidentInspectionTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentInspectionTask> IncidentInspectionTasks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectDeviationPhotoElement> ObjectDeviationPhotoElements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectDeviationPhotoElement> ObjectDeviationPhotoElements1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectInstancePhotoElement> ObjectInstancePhotoElements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectInstancePhotoElement> ObjectInstancePhotoElements1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectInstanceTask> ObjectInstanceTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectInstanceTask> ObjectInstanceTasks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkInspectionTask> WorkInspectionTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkInspectionTask> WorkInspectionTasks1 { get; set; }
    }
}
