//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRASInspection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FRASInspection()
        {
            this.FRASInspectionTasks = new HashSet<FRASInspectionTask>();
            this.Employees = new HashSet<Employee>();
        }
    
        public int FRASInspectionID { get; set; }
        public short FRASCheckListID { get; set; }
        public int LocationID { get; set; }
        public int ExecutedByUser { get; set; }
        public System.DateTime ExecutedDateTime { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CheckINDateTime { get; set; }
        public Nullable<System.DateTime> CheckOUTDateTime { get; set; }
        public bool IsMobileDeviceUsed { get; set; }
        public Nullable<bool> IsLocationLocatedWithQRCode { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<byte> ActualRiskLevelID { get; set; }
        public Nullable<double> ActualMarkValue { get; set; }
        public Nullable<byte> RiskLevelID { get; set; }
        public Nullable<double> MarkValue { get; set; }
        public Nullable<int> ResolvedBy { get; set; }
        public Nullable<System.DateTime> ResolutionDateTime { get; set; }
        public string ResolutionRemarks { get; set; }
        public Nullable<int> ClosedBy { get; set; }
        public Nullable<System.DateTime> ClosedDateTime { get; set; }
        public string ClosureRemarks { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual EndUser EndUser { get; set; }
        public virtual FRASCheckList FRASCheckList { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FRASInspectionTask> FRASInspectionTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
