//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRASInspectionTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FRASInspectionTask()
        {
            this.FRASInspectionPhotoes = new HashSet<FRASInspectionPhoto>();
        }
    
        public int FRASInspectionTaskID { get; set; }
        public int FRASInspectionID { get; set; }
        public int FRASCheckListTaskID { get; set; }
        public Nullable<bool> InspectionValueBit { get; set; }
        public Nullable<double> InspectionValueMark { get; set; }
        public string FRASInspectionRemarks { get; set; }
        public Nullable<bool> IsDeviation { get; set; }
        public Nullable<int> ResolvedBy { get; set; }
        public Nullable<System.DateTime> ResolutionDateTime { get; set; }
        public string ResolutionRemarks { get; set; }
        public Nullable<int> ClosedBy { get; set; }
        public Nullable<System.DateTime> ClosedDateTime { get; set; }
        public string ClosureRemarks { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual FRASCheckListTask FRASCheckListTask { get; set; }
        public virtual FRASInspection FRASInspection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FRASInspectionPhoto> FRASInspectionPhotoes { get; set; }
    }
}
