//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRASCheckListTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FRASCheckListTask()
        {
            this.FRASCheckListTaskLanguages = new HashSet<FRASCheckListTaskLanguage>();
            this.FRASInspectionTasks = new HashSet<FRASInspectionTask>();
        }
    
        public int FRASCheckListTaskID { get; set; }
        public short FRASCheckListID { get; set; }
        public short TaskSequence { get; set; }
        public bool IsMandatory { get; set; }
        public Nullable<short> CheckListTaskGroupID { get; set; }
        public string AttributeType { get; set; }
        public bool MarkIfTrue { get; set; }
        public int MarkIfTrueValue { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTill { get; set; }
    
        public virtual ChecklistTaskGroup ChecklistTaskGroup { get; set; }
        public virtual FRASCheckList FRASCheckList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FRASCheckListTaskLanguage> FRASCheckListTaskLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FRASInspectionTask> FRASInspectionTasks { get; set; }
    }
}
