//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRASRiskSetting
    {
        public string FRASInspectionType { get; set; }
        public byte RiskLevelID { get; set; }
        public Nullable<double> MinMarks { get; set; }
        public Nullable<double> MaxMarks { get; set; }
        public Nullable<System.DateTime> EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTill { get; set; }
    }
}
