//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Incident()
        {
            this.IncidentAttachments = new HashSet<IncidentAttachment>();
            this.IncidentCauses = new HashSet<IncidentCause>();
            this.IncidentDespatches = new HashSet<IncidentDespatch>();
            this.IncidentImpacts = new HashSet<IncidentImpact>();
            this.IncidentInspections = new HashSet<IncidentInspection>();
            this.IncidentLocations = new HashSet<IncidentLocation>();
            this.IncidentObjectInstances = new HashSet<IncidentObjectInstance>();
        }
    
        public int IncidentID { get; set; }
        public string IncidentTitle { get; set; }
        public Nullable<byte> IncidentTypeID { get; set; }
        public Nullable<short> IncidentCategoryID { get; set; }
        public Nullable<byte> IncidentSeverityLevel { get; set; }
        public Nullable<byte> IncidentPriorityLevel { get; set; }
        public Nullable<int> WaterQuantityUsed { get; set; }
        public System.DateTime OccurenceDateTime { get; set; }
        public int RecordedBy { get; set; }
        public System.DateTime RecordedDateTime { get; set; }
        public string ReportedBy { get; set; }
        public Nullable<System.DateTime> ReportedDateTime { get; set; }
        public string BriefDescription { get; set; }
        public string DetailedDescription { get; set; }
        public Nullable<int> IncidentOwner { get; set; }
        public byte IncidentStatus { get; set; }
        public string IncidentTag { get; set; }
        public Nullable<byte> ResolutionDuration { get; set; }
        public string ResolutionUnit { get; set; }
        public Nullable<int> ResolutionBy { get; set; }
        public Nullable<System.DateTime> ResolutionDateTime { get; set; }
        public string ResolutionRemarks { get; set; }
        public Nullable<int> ClosedBy { get; set; }
        public Nullable<System.DateTime> ClosureDateTime { get; set; }
        public string ClosureRemarks { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual IncidentCategory IncidentCategory { get; set; }
        public virtual IncidentStatu IncidentStatu { get; set; }
        public virtual IncidentType IncidentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentAttachment> IncidentAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentCause> IncidentCauses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentDespatch> IncidentDespatches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentImpact> IncidentImpacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentInspection> IncidentInspections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentLocation> IncidentLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentObjectInstance> IncidentObjectInstances { get; set; }
    }
}
