//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentImpact
    {
        public int IncidentID { get; set; }
        public byte IncidentImpactTypeID { get; set; }
        public string ImpactTitle { get; set; }
        public string Remarks { get; set; }
    
        public virtual Incident Incident { get; set; }
        public virtual IncidentImpactType IncidentImpactType { get; set; }
    }
}
