//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentInspection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IncidentInspection()
        {
            this.IncidentInspectionTasks = new HashSet<IncidentInspectionTask>();
        }
    
        public int IncidentInspectionID { get; set; }
        public int IncidentID { get; set; }
        public short IncidentChecklistID { get; set; }
        public Nullable<int> ExecutedByUser { get; set; }
    
        public virtual EndUser EndUser { get; set; }
        public virtual Incident Incident { get; set; }
        public virtual IncidentCheckList IncidentCheckList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentInspectionTask> IncidentInspectionTasks { get; set; }
    }
}
