//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentCheckListTaskView
    {
        public int IncidentCheckListTaskID { get; set; }
        public short IncidentCheckListID { get; set; }
        public Nullable<short> CheckListTaskGroupID { get; set; }
        public short TaskSequence { get; set; }
        public bool IsMandatory { get; set; }
        public string AttributeType { get; set; }
        public Nullable<short> TextLength { get; set; }
        public Nullable<byte> FloatPrecision { get; set; }
        public Nullable<byte> FloatScale { get; set; }
        public Nullable<short> UOMID { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTill { get; set; }
        public string LanguageCode { get; set; }
        public string IncidentCheckListTaskName { get; set; }
    }
}
