//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailLog
    {
        public long MailID { get; set; }
        public string MailType { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsMailFromFrontEnd { get; set; }
        public string FromMailID { get; set; }
        public string RecipientMailList { get; set; }
        public string CCMailList { get; set; }
        public string BCCMailList { get; set; }
        public string MailSubject { get; set; }
        public string Body { get; set; }
        public Nullable<long> MailItemID { get; set; }
    
        public virtual MailType MailType1 { get; set; }
    }
}
