//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectInstance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObjectInstance()
        {
            this.Deviations = new HashSet<Deviation>();
            this.ObjectDeviationPhotoes = new HashSet<ObjectDeviationPhoto>();
            this.IncidentObjectInstances = new HashSet<IncidentObjectInstance>();
            this.ObjectInstance1 = new HashSet<ObjectInstance>();
            this.ObjectInstanceInspections = new HashSet<ObjectInstanceInspection>();
            this.ObjectInstancePhotoElements = new HashSet<ObjectInstancePhotoElement>();
        }
    
        public int ObjectInstanceID { get; set; }
        public short ObjectID { get; set; }
        public int LocationID { get; set; }
        public string QRCode { get; set; }
        public string SerialNumber { get; set; }
        public string Make { get; set; }
        public Nullable<short> ObjectSequence { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<System.DateTime> WarrantyEndDate { get; set; }
        public Nullable<System.DateTime> AMCStartDate { get; set; }
        public Nullable<System.DateTime> AMCEndDate { get; set; }
        public System.DateTime EffectiveFromDate { get; set; }
        public Nullable<System.DateTime> EffectiveTillDate { get; set; }
        public Nullable<short> NotInUseReasonID { get; set; }
        public Nullable<int> PreviousObjectInstanceID { get; set; }
        public string SourceRefID { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deviation> Deviations { get; set; }
        public virtual Location Location { get; set; }
        public virtual NotInUseReason NotInUseReason { get; set; }
        public virtual Object Object { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectDeviationPhoto> ObjectDeviationPhotoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentObjectInstance> IncidentObjectInstances { get; set; }
        public virtual ObjectInstanceMake ObjectInstanceMake { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectInstance> ObjectInstance1 { get; set; }
        public virtual ObjectInstance ObjectInstance2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectInstanceInspection> ObjectInstanceInspections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectInstancePhotoElement> ObjectInstancePhotoElements { get; set; }
    }
}
