//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectDeviationPhoto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObjectDeviationPhoto()
        {
            this.ObjectDeviationPhotoElements = new HashSet<ObjectDeviationPhotoElement>();
        }
    
        public int ObjectInstanceID { get; set; }
        public System.DateTime PhotoDateTime { get; set; }
        public Nullable<long> DeviationID { get; set; }
        public string Remarks { get; set; }
    
        public virtual Deviation Deviation { get; set; }
        public virtual ObjectInstance ObjectInstance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectDeviationPhotoElement> ObjectDeviationPhotoElements { get; set; }
    }
}
