//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectInstanceInspection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObjectInstanceInspection()
        {
            this.ObjectInstanceTasks = new HashSet<ObjectInstanceTask>();
        }
    
        public long ObjectInstanceInspectionID { get; set; }
        public int InspectionID { get; set; }
        public int ObjectInstanceID { get; set; }
        public System.DateTime InspectionDateTime { get; set; }
        public int ControllerID { get; set; }
        public bool IsMobileDeviceUsed { get; set; }
        public Nullable<bool> IsObjectLocatedWithQRCode { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
    
        public virtual EndUser EndUser { get; set; }
        public virtual Inspection Inspection { get; set; }
        public virtual ObjectInstance ObjectInstance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectInstanceTask> ObjectInstanceTasks { get; set; }
    }
}
