//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectInstanceTask
    {
        public long ObjectInstanceInspectionID { get; set; }
        public int CheckListTaskID { get; set; }
        public Nullable<bool> InspectionValueBit { get; set; }
        public Nullable<double> InspectionValueFloat { get; set; }
        public Nullable<System.DateTime> InspectionValueDateTime { get; set; }
        public string InspectionValueString { get; set; }
        public Nullable<long> InspectionValuePhoto { get; set; }
        public Nullable<long> InspectionValueSmallPhoto { get; set; }
    
        public virtual CheckListTask CheckListTask { get; set; }
        public virtual FolderFile FolderFile { get; set; }
        public virtual FolderFile FolderFile1 { get; set; }
        public virtual ObjectInstanceInspection ObjectInstanceInspection { get; set; }
    }
}
