//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectAttribute
    {
        public short ObjectID { get; set; }
        public short AttributeID { get; set; }
        public Nullable<bool> ValueBit { get; set; }
        public Nullable<double> ValueFloat { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public string ValueText { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual Object Object { get; set; }
    }
}
