//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreenAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScreenAction()
        {
            this.UserRoleScreenActions = new HashSet<UserRoleScreenAction>();
        }
    
        public short ScreenID { get; set; }
        public string ActionCode { get; set; }
        public string ActionName { get; set; }
        public byte Sequence { get; set; }
        public bool IsAudited { get; set; }
        public bool IsRendered { get; set; }
    
        public virtual Screen Screen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRoleScreenAction> UserRoleScreenActions { get; set; }
    }
}
