//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingAssessment
    {
        public int TrainingAssessmentID { get; set; }
        public short TrainingEnrolmentID { get; set; }
        public int AssessmentParameterID { get; set; }
        public string AssessmentValue { get; set; }
    
        public virtual AssessmentParameter AssessmentParameter { get; set; }
        public virtual TrainingEnrolment TrainingEnrolment { get; set; }
    }
}
