//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingTrainer
    {
        public int TrainingID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string TrainerName { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Training Training { get; set; }
    }
}
