//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Training()
        {
            this.TrainingEnrolments = new HashSet<TrainingEnrolment>();
        }
    
        public int TrainingID { get; set; }
        public short CourseID { get; set; }
        public System.DateTime EffectiveFromDateTime { get; set; }
        public System.DateTime EffectiveTillDateTime { get; set; }
        public int CreatedBy { get; set; }
        public string Remarks { get; set; }
        public Nullable<short> CertificationID { get; set; }
        public bool IsExternalTraining { get; set; }
        public string TrainingLocation { get; set; }
        public string SourceRefID { get; set; }
        public bool EnrolmentRequired { get; set; }
        public Nullable<int> EvidenceDocument { get; set; }
        public Nullable<short> AttendanceCount { get; set; }
        public short CustomerID { get; set; }
    
        public virtual Certification Certification { get; set; }
        public virtual Course Course { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual EndUser EndUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingEnrolment> TrainingEnrolments { get; set; }
        public virtual TrainingTrainer TrainingTrainer { get; set; }
    }
}
