//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingEnrolment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainingEnrolment()
        {
            this.TrainingAssessments = new HashSet<TrainingAssessment>();
            this.TrainingFeedbacks = new HashSet<TrainingFeedback>();
        }
    
        public short TrainingEnrolmentID { get; set; }
        public int TrainingID { get; set; }
        public Nullable<int> TraineeID { get; set; }
        public string TraineeName { get; set; }
        public string TraineeEmail { get; set; }
        public string TraineeOrganization { get; set; }
        public System.DateTime EnrolmentDateTime { get; set; }
        public Nullable<bool> HasAttended { get; set; }
        public string CancellationRemarks { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> TrainerID { get; set; }
        public string TrainerName { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Training Training { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingAssessment> TrainingAssessments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingFeedback> TrainingFeedbacks { get; set; }
    }
}
