//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingFeedback
    {
        public int TrainingFeedbackID { get; set; }
        public short TrainingEnrolmentID { get; set; }
        public short FeedbackParameterValueID { get; set; }
    
        public virtual FeedbackParameterValue FeedbackParameterValue { get; set; }
        public virtual TrainingEnrolment TrainingEnrolment { get; set; }
    }
}
