//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoleScreen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserRoleScreen()
        {
            this.UserRoleScreenActions = new HashSet<UserRoleScreenAction>();
        }
    
        public short UserRoleID { get; set; }
        public short ScreenID { get; set; }
        public bool HasInsert { get; set; }
        public bool HasUpdate { get; set; }
        public bool HasDelete { get; set; }
        public bool HasSelect { get; set; }
        public bool HasImport { get; set; }
        public bool HasExport { get; set; }
    
        public virtual Screen Screen { get; set; }
        public virtual UserRole UserRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRoleScreenAction> UserRoleScreenActions { get; set; }
    }
}
