//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkInspection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkInspection()
        {
            this.WorkInspectionTasks = new HashSet<WorkInspectionTask>();
        }
    
        public int WorkInspectionID { get; set; }
        public short WorkChecklistID { get; set; }
        public Nullable<int> ExecutedByUser { get; set; }
        public System.DateTime WorkInspectionDateTime { get; set; }
    
        public virtual EndUser EndUser { get; set; }
        public virtual WorkCheckList WorkCheckList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkInspectionTask> WorkInspectionTasks { get; set; }
    }
}
