//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkPermit
    {
        public int WorkPermitID { get; set; }
        public short WorkPermitTypeID { get; set; }
        public string WPTitle { get; set; }
        public System.DateTime WPRecordedDateTime { get; set; }
        public int WPRecordedBy { get; set; }
        public string RequesterName { get; set; }
        public string RequesterCompany { get; set; }
        public string RequesterMobile { get; set; }
        public string RequesterEmail { get; set; }
        public int Location { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public System.DateTime EffectiveTill { get; set; }
        public System.TimeSpan WorkFrom { get; set; }
        public System.TimeSpan WorkTill { get; set; }
        public Nullable<short> PeopleCount { get; set; }
        public string SupervisorName { get; set; }
        public string HelperName { get; set; }
        public string Remarks { get; set; }
        public string SafetyEquipment { get; set; }
        public string ApprovalRemarks { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDatetime { get; set; }
        public string CancellationRemarks { get; set; }
        public Nullable<int> CancelledBy { get; set; }
        public Nullable<System.DateTime> CancellationDatetime { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual EndUser EndUser { get; set; }
        public virtual WorkPermitType WorkPermitType { get; set; }
    }
}
