//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Business.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkCheckListTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkCheckListTask()
        {
            this.WorkCheckListTaskLanguages = new HashSet<WorkCheckListTaskLanguage>();
            this.WorkInspectionTasks = new HashSet<WorkInspectionTask>();
        }
    
        public int WorkCheckListTaskID { get; set; }
        public short WorkCheckListID { get; set; }
        public short TaskSequence { get; set; }
        public bool IsMandatory { get; set; }
        public Nullable<short> ChecklistTaskGroupID { get; set; }
        public string AttributeType { get; set; }
        public Nullable<short> TextLength { get; set; }
        public Nullable<byte> FloatPrecision { get; set; }
        public Nullable<byte> FloatScale { get; set; }
        public Nullable<short> UOMID { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTill { get; set; }
    
        public virtual ChecklistTaskGroup ChecklistTaskGroup { get; set; }
        public virtual UOM UOM { get; set; }
        public virtual WorkCheckList WorkCheckList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkCheckListTaskLanguage> WorkCheckListTaskLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkInspectionTask> WorkInspectionTasks { get; set; }
    }
}
